# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022-2023, NVIDIA CORPORATION.  All rights reserved.

obj-m += nvmap/
obj-m += host/nvdla/
obj-m += host/pva/
obj-m += tsec/
obj-m += dc/bridge/
obj-m += camera/
obj-m += host/capture/
obj-m += host/nvcsi/
obj-m += host/vi/
obj-m += host/isp/
obj-m += virt/
