# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

obj-m += cdi/
obj-m += isc/
obj-m += camera/
obj-m += tpg/
obj-m += cam_fsync/
